// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO refresh_tokens(id, expires_at, user_id)
VALUES($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    id = EXCLUDED.id,
    expires_at = EXCLUDED.expires_at,
    user_id = EXCLUDED.user_id
RETURNING id, created_at, updated_at, expires_at, revoked_at, user_id
`

type CreateTokenParams struct {
	ID        string
	ExpiresAt time.Time
	UserID    uuid.UUID
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createToken, arg.ID, arg.ExpiresAt, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, created_at, updated_at, expires_at, revoked_at, user_id
FROM refresh_tokens
WHERE id = $1
`

func (q *Queries) GetTokenByID(ctx context.Context, id string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getTokenByID, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const getTokenByUserID = `-- name: GetTokenByUserID :one
SELECT id, created_at, updated_at, expires_at, revoked_at, user_id
FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) GetTokenByUserID(ctx context.Context, userID uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getTokenByUserID, userID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens
SET expires_at = $1, updated_at = $2
WHERE id = $3
`

type RevokeTokenParams struct {
	ExpiresAt time.Time
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeToken, arg.ExpiresAt, arg.UpdatedAt, arg.ID)
	return err
}
